import { IsString, MinLength, MaxLength } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class CreateCardDto {
  @ApiProperty({ description: 'Card token generated by MercadoPago.js (never the PAN)' })
  @IsString()
  @MinLength(8)
  @MaxLength(200)
  token: string;
}