import {
  IsString,
  IsOptional,
  IsBoolean,
  IsInt,
  Min,
  Max,
  Length,
  ValidateIf,
  IsUUID,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class CreatePaymentDto {
  @ApiProperty()
  @IsUUID()
  orderId: string;

  @ApiPropertyOptional({ description: 'Saved card id' })
  @ValidateIf((o) => !o.cardToken)
  @IsUUID()
  cardId?: string;

  @ApiPropertyOptional({ description: 'Card token generated by MercadoPago.js' })
  @ValidateIf((o) => !o.cardId)
  @IsString()
  @Length(8, 200)
  cardToken?: string;

  @ApiPropertyOptional({ description: 'Whether to save the new card for future purchases' })
  @IsOptional()
  @IsBoolean()
  saveCard?: boolean;

  @ApiPropertyOptional({ default: 1 })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(12)
  installments?: number;
}